import { useEffect, useMemo, useState } from 'react';
import { Box, Button, Card, Dialog, DialogActions, DialogContent, DialogTitle, Fab, Grid, MenuItem, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import dayjs from 'dayjs';
import { agregarEmpleado, agregarHorario, listenEmpleados, listenHorarios } from '../../services/nominas/nominasService.js';
import { formatMoney } from '../../utils/date.js';

export default function Nominas(){
 const [empleados,setEmpleados]=useState([]);const [horarios,setHorarios]=useState([]);const [open,setOpen]=useState(null);
 const [periodo,setPeriodo]=useState({inicio:dayjs().startOf('week').format('YYYY-MM-DD'),fin:dayjs().endOf('week').format('YYYY-MM-DD')});
 const [emp,setEmp]=useState({nombre:'',puesto:'',pagoHora:''});const [hora,setHora]=useState({empleadoId:'',fecha:dayjs().format('YYYY-MM-DD'),entrada:'08:00',salida:'17:00'});
 useEffect(()=>listenEmpleados(setEmpleados),[]);useEffect(()=>listenHorarios(periodo.inicio,periodo.fin,setHorarios),[periodo.inicio,periodo.fin]);
 const resumen=useMemo(()=>empleados.map(e=>{const hs=horarios.filter(h=>h.empleadoId===e.id).reduce((s,h)=>s+Number(h.horas||0),0);return {...e,horas:hs,total:hs*Number(e.pagoHora||0)}}),[empleados,horarios]);
 const calcHoras=()=>{const a=dayjs(`${hora.fecha} ${hora.entrada}`);const b=dayjs(`${hora.fecha} ${hora.salida}`);return Math.max(0,b.diff(a,'minute')/60)};
 return <Box><Stack direction="row" justifyContent="space-between" mb={2}><Typography variant="h5">Nóminas</Typography><Stack direction="row" gap={1}><Button onClick={()=>setOpen('empleado')}>Agregar empleado</Button><Button onClick={()=>setOpen('horario')}>Agregar horas</Button></Stack></Stack><Grid container spacing={2} mb={2}><Grid item xs={6}><TextField fullWidth type="date" label="Inicio" value={periodo.inicio} onChange={e=>setPeriodo({...periodo,inicio:e.target.value})} InputLabelProps={{shrink:true}} /></Grid><Grid item xs={6}><TextField fullWidth type="date" label="Fin" value={periodo.fin} onChange={e=>setPeriodo({...periodo,fin:e.target.value})} InputLabelProps={{shrink:true}} /></Grid></Grid><Card><Table><TableHead><TableRow><TableCell>Empleado</TableCell><TableCell>Puesto</TableCell><TableCell>Pago/Hora</TableCell><TableCell>Horas</TableCell><TableCell>Total</TableCell></TableRow></TableHead><TableBody>{resumen.map(r=><TableRow key={r.id}><TableCell>{r.nombre}</TableCell><TableCell>{r.puesto}</TableCell><TableCell>{formatMoney(r.pagoHora)}</TableCell><TableCell>{r.horas}</TableCell><TableCell>{formatMoney(r.total)}</TableCell></TableRow>)}</TableBody></Table></Card><Fab color="primary" sx={{position:'fixed',right:32,bottom:32}} onClick={()=>setOpen('horario')}><AddIcon/></Fab>
 <Dialog open={open==='empleado'} onClose={()=>setOpen(null)} fullWidth maxWidth="sm"><DialogTitle>Agregar empleado</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:1}}><TextField label="Nombre" value={emp.nombre} onChange={e=>setEmp({...emp,nombre:e.target.value})}/><TextField label="Puesto" value={emp.puesto} onChange={e=>setEmp({...emp,puesto:e.target.value})}/><TextField label="Pago por hora" type="number" value={emp.pagoHora} onChange={e=>setEmp({...emp,pagoHora:e.target.value})}/></DialogContent><DialogActions><Button variant="text" onClick={()=>setOpen(null)}>Cancelar</Button><Button onClick={async()=>{await agregarEmpleado({...emp,pagoHora:Number(emp.pagoHora)});setEmp({nombre:'',puesto:'',pagoHora:''});setOpen(null)}}>Guardar</Button></DialogActions></Dialog>
 <Dialog open={open==='horario'} onClose={()=>setOpen(null)} fullWidth maxWidth="sm"><DialogTitle>Agregar horas</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:1}}><TextField select label="Empleado" value={hora.empleadoId} onChange={e=>setHora({...hora,empleadoId:e.target.value})}>{empleados.map(e=><MenuItem key={e.id} value={e.id}>{e.nombre}</MenuItem>)}</TextField><TextField type="date" label="Fecha" value={hora.fecha} onChange={e=>setHora({...hora,fecha:e.target.value})} InputLabelProps={{shrink:true}}/><TextField type="time" label="Entrada" value={hora.entrada} onChange={e=>setHora({...hora,entrada:e.target.value})} InputLabelProps={{shrink:true}}/><TextField type="time" label="Salida" value={hora.salida} onChange={e=>setHora({...hora,salida:e.target.value})} InputLabelProps={{shrink:true}}/></DialogContent><DialogActions><Button variant="text" onClick={()=>setOpen(null)}>Cancelar</Button><Button onClick={async()=>{await agregarHorario({...hora,horas:calcHoras()});setOpen(null)}}>Guardar horas</Button></DialogActions></Dialog></Box>}
